# Generated by Django 4.1.5 on 2023-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Whey Protein', 'Whey Protein'), ('Creatine', 'Creatine'), ('Pre Workout', 'Pre Workout')], default=None, max_length=200)),
                ('image_url', models.CharField(default=None, max_length=200)),
                ('size', models.CharField(choices=[('1KG', '1KG'), ('500GM', '500GM'), ('250GM', '250GM'), ('100GM', '100GM')], default=None, max_length=20)),
                ('flavour', models.CharField(choices=[('Chocolate', 'Chocolate'), ('Vanilla', 'Vanilla'), ('Butter scotch', 'Butter scotch'), ('Pista', 'Pista')], default=None, max_length=20)),
                ('mrp', models.IntegerField(default=None)),
                ('discount', models.IntegerField(default=None)),
            ],
        ),
    ]
