# Generated by Django 4.1.5 on 2023-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_discount_alter_product_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticity',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
