# Generated by Django 4.1.5 on 2023-02-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='feedback',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
