# Generated by Django 4.1.5 on 2023-02-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_name',
            new_name='cart_details',
        ),
    ]
