# Generated by Django 4.1.5 on 2023-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_reviews_feedback'),
        ('user', '0003_rename_product_name_cart_cart_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_details',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_details',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
